version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8000"
    command: sh ./entrypoint.sh
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: mysql
    environment:
      MYSQL_DATABASE: 'youtube_database'
      MYSQL_ROOT_PASSWORD: 'password'
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - production_db_volume:/var/lib/mysql

volumes:
  production_db_volume: